apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  purpose: kubernetes demo

commonLabels:
  app: sliced-bread

namespace: sliced-bread-demo

secretGenerator:
  - name: mysql-pass
    literals:
      - password=admin

configMapGenerator:
  - name: wordpress-config
    files:
      - wp-config.php

resources:
  - mysql-service.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - wordpress-service.yaml
  - wordpress-pvc.yaml
  - wordpress-deployment.yaml
  - wordpress-route.yaml
